// src/EmoteBuilder.tsx
import * as React from 'react';
import './EmoteBuilder.css';
import { IEmoteDataEntry, EmoteExpander, EmoteExpansionOptions } from 'emotes';
import { EmoteForm } from './EmoteForm';
// import * as EmoteLib from 'emotes';

export class EmoteBuilder extends React.Component {
    emoteData: IEmoteDataEntry[];
    // emoteMap: EmoteMap;
    // emoteHtml: EmoteHtml;
    emoteExpander: EmoteExpander;
    emoteExpansionOptions = new EmoteExpansionOptions();
    // emoteParser = new EmoteParser();
    // emoteObjectSerializer = new EmoteObjectSerializer();

    useEmoteData(emoteData: IEmoteDataEntry[]) {
        this.emoteData = emoteData;
        this.emoteExpander = new EmoteExpander(emoteData, this.emoteExpansionOptions);

    // since the updated emote data might be needed for the 
    // expansion of the current emote string, force a refresh here
        // this.refreshExpandedEmotes(); 
    }

    render() {
        return (
            <div className="container-fluid theme-showcase" role="main">
                bogus content here v2
                <EmoteForm />
            </div>
        );
    }

    ngOnInit() {
        // console.log(`something is ${this.something}`);
        // console.log(`initialEmoteData is ${this.initialEmoteData}`);
    //     // populate with some initial emote data so the page can render the default emote objects
    //     this.useEmoteData(this.initialEmoteData);
    //     // kick off the fetch of the real emote data
    //     this.populateEmoteData();

    //     const encodedEmoteString = this.router.routerState.snapshot.queryParams['emoteString'];
    //     if (encodedEmoteString) {
    //         this.existingEmoteString = decodeURIComponent(encodedEmoteString);
    //         this.importExistingEmoteString();
    //         this.router.navigate([''], { queryParams: {} }); // navigate to get rid of the query param
    //     }

    //     this.refreshSerializedEmotes();
    //     this.refreshExpandedEmotes();
    }

    // onNumberOfEmotesChanged() {
    //     if (this.numberOfEmotes < this.emoteObjects.length) {
    //         // truncating
    //         this.emoteObjects.length = this.numberOfEmotes;
    //     } else {
    //         // expanding, so fill in new ones as needed
    //         while (this.emoteObjects.length < this.numberOfEmotes) {
    //             const defaultEmoteInSlot = this.defaultEmoteObjects[this.emoteObjects.length];
    //             this.emoteObjects.push(defaultEmoteInSlot);
    //         }
    //     }
    //     this.refreshSerializedAndExpandedEmotes();
    // }

    // private initialEmoteData: IEmoteDataEntry[] = [
    //     {
    //         'text-text-align': 'center',
    //         'text-font-size': '26px',
    //         'text-font-family': 'Impact,sans-serif',
    //         'tags': ['applejack', 'meme'],
    //         'strong-bottom': '5px',
    //         'text-text-shadow': '2px 2px 2px black,-2px -2px 2px black,-2px 2px 2px black,2px -2px 2px black',
    //         'height': 300,
    //         'em-width': '280px',
    //         'strong-left': '50%',
    //         'names': ['adviceajlie'],
    //         'em-position': 'absolute',
    //         'strong-position': 'absolute',
    //         'background-image': 'http://b.thumbs.redditmedia.com/5g6WH3RD7F5aMC-O.png',
    //         'em-font-style': 'normal',
    //         'em-color': 'white',
    //         'em-top': '5px',
    //         'width': 300,
    //         'sr': 'adviceponies',
    //         'strong-color': 'white',
    //         'strong-margin-left': '-140px',
    //         'text-color': 'white',
    //         'strong-width': '280px',
    //         'em-left': '50%',
    //         'text-text-transform': 'uppercase',
    //         'strong-font-weight': 'normal',
    //         'background-position': ['-2px', '-2px'],
    //         'text-line-height': '26px',
    //         'em-margin-left': '-140px'
    //     },
    //     {
    //         "background-image": "//a.thumbs.redditmedia.com/84ozl2WMmiYp6Euf.png",
    //         "tags": ["oc", ""],
    //         "sr": "marmemotes",
    //         "height": 140,
    //         "width": 200,
    //         "names": ["ivyrage", "ierage"],
    //         "apng_url": "http://berrymotes.com/images/a/84ozl2WMmiYp6Euf.png"
    //     },
    // ];
  
    // private defaultEmoteObjects: EmoteObject[] = [
    //     EmoteObjectBuilder.create({
    //         emoteIdentifier: 'adviceajlie',
    //         firstLineText: 'apples?',
    //         secondLineText: 'I didn\'t see any apples',
    //     }),
    //     EmoteObjectBuilder.create({
    //         emoteIdentifier: 'twiright',
    //     }),
    //     EmoteObjectBuilder.create({
    //         emoteIdentifier: 'hahaha',
    //     }),
    //     EmoteObjectBuilder.create({
    //         emoteIdentifier: 'rdwut',
    //     }),
    // ];

    // numberOfEmotes = 2;

    // // clone since we don't want to modify the original set of default objects
    // public emoteObjects: EmoteObject[] = [
    //     EmoteObjectBuilder.clone(this.defaultEmoteObjects[0]),
    //     EmoteObjectBuilder.clone(this.defaultEmoteObjects[1]),
    // ];

    // existingEmoteString: string;

    // escapeHtml = function (str) {
    //     var div = document.createElement('div');
    //     div.appendChild(document.createTextNode(str));
    //     return div.innerHTML;
    // };
  
    // private populateEmoteData() {
    //     return this.http.get('//berrymotes.com/assets/berrymotes_json_data.json')
    //         .map(this.extractData)
    //         .catch(this.handleError)
    //         .subscribe(emoteData => this.useEmoteData(emoteData));
    // } 
  
    // private extractData(res: Response): IEmoteDataEntry[] {
    //     return res.json();
    // }
  
    // private handleError(error: any) {
    //     let errMsg = (error.message) ? error.message :
    //         error.status ? `${error.status} - ${error.statusText}` : 'Server error';
    //     console.error(errMsg); // log to console instead
    //     return Observable.throw(errMsg);
    // }

    // expandedEmotes: string;
    // serializedEmotes: string;
    // get encodedSerializedEmotes(): string { return encodeURIComponent(this.serializedEmotes); }

    // get linkForCurrentSettings(): string {
    //     const appRelativeUrl = this.router.createUrlTree(
            //     [''], 
            //     { queryParams: { emoteString: this.encodedSerializedEmotes } }
            // ).toString();
    //     // TODO: figure out the right way to make this into an absolute url
    //     const absoluteUrl = location.href + appRelativeUrl.substring(1);
    //     return absoluteUrl;
    // }

    // onEmoteObjectChanged() {
    //     this.refreshSerializedAndExpandedEmotes();
    // }

    // refreshSerializedAndExpandedEmotes() {
    //     this.refreshSerializedEmotes();
    //     this.refreshExpandedEmotes();
    // }

    // refreshSerializedEmotes() {
    //     this.serializedEmotes = this.emoteObjects
    //         .map(eo => this.emoteObjectSerializer.serialize(eo))
    //         .join(' ');
    // }

    // refreshExpandedEmotes() {
    //     this.expandedEmotes = this.emoteObjects
    //         .map(eo => this.emoteHtml.getEmoteHtmlForObject(eo))
    //         .join(' ');
    // }

    // importExistingEmoteString() {
    //     var emoteInfos = this.emoteParser.parseMultipleEmotes(this.existingEmoteString);

    //     if (emoteInfos && emoteInfos.length > 0) {
    //         this.emoteObjects = emoteInfos;
    //         this.numberOfEmotes = this.emoteObjects.length;
    //         this.refreshSerializedAndExpandedEmotes();
    //     }
    //     this.existingEmoteString = null;
    // };
}

// src/app/emote-builder/emote-builder.component.ts
import {
  Component,
  Pipe,
  PipeTransform,
  OnInit,
  OnChanges,
  OnDestroy,
  Input,
} from '@angular/core';
import {DomSanitizationService} from '@angular/platform-browser';
import { Http, Response } from '@angular/http';
import { Router, ROUTER_DIRECTIVES } from '@angular/router';
import { Location } from '@angular/common';
import {AlertComponent} from 'ng2-bootstrap/ng2-bootstrap';

import {
  EmoteObject,
  EmoteObjectBuilder,
  EmoteMap,
  EmoteExpander,
  EmoteExpansionOptions,
  EmoteFlags,
  EmoteHtml,
  EmoteObjectSerializer,
  EmoteParser,
  IEmoteDataEntry,
} from '../shared/';
import { SafePipe } from '../safe.pipe';
import { EmoteFormComponent } from '../emote-form/'
import { Observable }     from 'rxjs/Observable';
import {ClipboardDirective} from 'angular2-clipboard';
import '../rxjs-operators';

@Component({
  moduleId: module.id,
  selector: 'emote-builder',
  templateUrl: 'emote-builder.component.html',
  styleUrls: ['emote-builder.component.css'],
  directives: [EmoteFormComponent, ClipboardDirective, ROUTER_DIRECTIVES, AlertComponent],
  pipes: [SafePipe],
})
export class EmoteBuilderComponent implements OnInit {
  constructor (
    private http: Http, 
    private router: Router, 
    private location: Location) {}

  ngOnInit() {
    // populate with some initial emote data so the page can render the default emote objects
    this.useEmoteData(this.initialEmoteData);
    // kick off the fetch of the real emote data
    this.populateEmoteData();

    const encodedEmoteString = this.router.routerState.snapshot.queryParams['emoteString'];
    if (encodedEmoteString) {
      this.existingEmoteString = decodeURIComponent(encodedEmoteString);
      this.importExistingEmoteString();
      this.router.navigate([''], {queryParams: {}}); // navigate to get rid of the query param
    }

    this.refreshSerializedEmotes();
    this.refreshExpandedEmotes();
  }

  onNumberOfEmotesChanged() {
    if (this.numberOfEmotes < this.emoteObjects.length) {
      // truncating
      this.emoteObjects.length = this.numberOfEmotes;
    } else {
      // expanding, so fill in new ones as needed
      while (this.emoteObjects.length < this.numberOfEmotes) {
        const defaultEmoteInSlot = this.defaultEmoteObjects[this.emoteObjects.length];
        this.emoteObjects.push(defaultEmoteInSlot);
      }
    }
    this.refreshSerializedAndExpandedEmotes();
  }

  private initialEmoteData = <IEmoteDataEntry[]> [
    {
      'text-text-align': 'center',
      'text-font-size': '26px',
      'text-font-family': 'Impact,sans-serif',
      'tags': ['applejack', 'meme'],
      'strong-bottom': '5px',
      'text-text-shadow': '2px 2px 2px black,-2px -2px 2px black,-2px 2px 2px black,2px -2px 2px black',
      'height': 300,
      'em-width': '280px',
      'strong-left': '50%',
      'names': ['adviceajlie'],
      'em-position': 'absolute',
      'strong-position': 'absolute',
      'background-image': 'http://b.thumbs.redditmedia.com/5g6WH3RD7F5aMC-O.png',
      'em-font-style': 'normal',
      'em-color': 'white',
      'em-top': '5px',
      'width': 300,
      'sr': 'adviceponies',
      'strong-color': 'white',
      'strong-margin-left': '-140px',
      'text-color': 'white',
      'strong-width': '280px',
      'em-left': '50%',
      'text-text-transform': 'uppercase',
      'strong-font-weight': 'normal',
      'background-position': ['-2px', '-2px'],
      'text-line-height': '26px',
      'em-margin-left': '-140px'
    },
    {
      "background-image": "//a.thumbs.redditmedia.com/84ozl2WMmiYp6Euf.png",
      "tags": ["oc", ""],
      "sr": "marmemotes",
      "height": 140,
      "width": 200,
      "names": ["ivyrage", "ierage"],
      "apng_url": "http://berrymotes.com/images/a/84ozl2WMmiYp6Euf.png"
    },
  ];

  emoteData: IEmoteDataEntry[];
  emoteMap: EmoteMap;
  emoteHtml: EmoteHtml;
  emoteExpander: EmoteExpander;
  emoteExpansionOptions = new EmoteExpansionOptions();
  emoteParser = new EmoteParser();
  emoteObjectSerializer = new EmoteObjectSerializer();

  useEmoteData(emoteData: IEmoteDataEntry[]) {
    this.emoteData = emoteData;
    this.emoteMap = new EmoteMap(this.emoteData);
    this.emoteHtml = new EmoteHtml(this.emoteMap, this.emoteExpansionOptions);
    this.emoteExpander = new EmoteExpander(this.emoteMap, this.emoteHtml, this.emoteParser);

    this.refreshExpandedEmotes(); // since the updated emote data might be needed for the expansion of the current emote string, force a refresh here
  }

  private defaultEmoteObjects: EmoteObject[] = [
    EmoteObjectBuilder.create({
      emoteIdentifier: 'adviceajlie',
      firstLineText: 'apples?',
      secondLineText: 'I didn\'t see any apples',
    }),
    EmoteObjectBuilder.create({
      emoteIdentifier: 'twiright',
    }),
    EmoteObjectBuilder.create({
      emoteIdentifier: 'hahaha',
    }),
    EmoteObjectBuilder.create({
      emoteIdentifier: 'rdwut',
    }),
  ];

  @Input() numberOfEmotes = 2;

  // clone since we don't want to modify the original set of default objects
  @Input() public emoteObjects: EmoteObject[] = [
    EmoteObjectBuilder.clone(this.defaultEmoteObjects[0]),
    EmoteObjectBuilder.clone(this.defaultEmoteObjects[1]),
  ];

  existingEmoteString: string;

  escapeHtml = function (str) {
    var div = document.createElement('div');
    div.appendChild(document.createTextNode(str));
    return div.innerHTML;
  };

  private populateEmoteData() {
    return this.http.get('//berrymotes.com/assets/berrymotes_json_data.json')
             .map(this.extractData)
             .catch(this.handleError)
             .subscribe(emoteData => this.useEmoteData(emoteData));
  } 

  private extractData(res: Response): IEmoteDataEntry[] {
    return res.json();
  }

  private handleError (error: any) {
    let errMsg = (error.message) ? error.message :
      error.status ? `${error.status} - ${error.statusText}` : 'Server error';
    console.error(errMsg); // log to console instead
    return Observable.throw(errMsg);
  }

  expandedEmotes: string;
  serializedEmotes: string;
  get encodedSerializedEmotes(): string { return encodeURIComponent(this.serializedEmotes); }

  get linkForCurrentSettings(): string { 
    const appRelativeUrl = this.router.createUrlTree([''], {queryParams: {emoteString: this.encodedSerializedEmotes}}).toString();
    // TODO: figure out the right way to make this into an absolute url
    const absoluteUrl = location.href + appRelativeUrl.substring(1);
    return absoluteUrl;
  }

  onEmoteObjectChanged() {
    this.refreshSerializedAndExpandedEmotes();
  }

  refreshSerializedAndExpandedEmotes() {
    this.refreshSerializedEmotes();
    this.refreshExpandedEmotes();
  }

  refreshSerializedEmotes() {
    this.serializedEmotes = this.emoteObjects
      .map(eo => this.emoteObjectSerializer.serialize(eo))
      .join(' ');
  }

  refreshExpandedEmotes() {
    this.expandedEmotes = this.emoteObjects
      .map(eo =>this.emoteHtml.getEmoteHtmlForObject(eo))
      .join(' ');
  }

  importExistingEmoteString() {
    var emoteInfos = this.emoteParser.parseMultipleEmotes(this.existingEmoteString);

    if (emoteInfos && emoteInfos.length > 0) {
      this.emoteObjects = emoteInfos;
      this.numberOfEmotes = this.emoteObjects.length;
      this.refreshSerializedAndExpandedEmotes();
    }
    this.existingEmoteString = null;
  };
}

    <div class="container theme-showcase" role="main">

<alert dismissOnTimeout="3000" type="info">ng2-bootstrap hello world!</alert>


<div class="row">
    <div class="col-md-6">
        <label>Number of emotes:
            <select [(ngModel)]="numberOfEmotes" (ngModelChange)="onNumberOfEmotesChanged()">
                <option>1</option>
                <option>2</option>
            </select>
        </label>
        <button class='btn btn-primary' *ngIf="numberOfEmotes == 2" (click)="swapEmotes()">Swap emote 1 and emote 2</button>
    </div>
    <div class="col-md-6">
        <form (ngSubmit)="importExistingEmoteString()" class="form-horizontal">
            <label>Import existing emote string:
                <input type="text" name="existingEmoteString" [(ngModel)]="existingEmoteString" placeholder="like [](/ajlie)">
            </label>
            <button class='btn btn-primary' type="submit">Import</button>
        </form>
    </div>
</div>

        
<br/>



      <div class="row" *ngIf="numberOfEmotes == 1">
        <div class="col-md-12">
            <app-emote-form [emoteMap]="emoteMap" [emoteObject]="emoteObject1" (emoteObjectChanged)="onEmoteObjectChanged($event)"></app-emote-form>
        </div>
      </div>

      <div class="row" *ngIf="numberOfEmotes == 2">
        <div class="col-md-6">
            <h2>Emote #1</h2>
            <app-emote-form [emoteMap]="emoteMap" [emoteObject]="emoteObject1" (emoteObjectChanged)="onEmoteObjectChanged($event)"></app-emote-form>
        </div>
        <div class="col-md-6">
            <h2>Emote #2</h2>
            <app-emote-form [emoteMap]="emoteMap" [emoteObject]="emoteObject2" (emoteObjectChanged)="onEmoteObjectChanged($event)"></app-emote-form>
        </div>
      </div>

<h3>Output</h3>

<div class="row">
  <div class="col-sm-12">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="button" ngIIclipboard [cbContent]="serializedEmotes">copy emote string to clipboard</button>
      </span>
      <input type="text" class="form-control" [ngModel]="serializedEmotes" readonly>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="button" ngIIclipboard [cbContent]="linkForCurrentSettings">copy link for current settings to clipboard</button>
      </span>
      <input type="text" class="form-control" [ngModel]="linkForCurrentSettings" readonly>
    </div>
  </div>
</div>

<br>

    <div id="expandedEmotes" style="background-color: white"></div>

    <div [innerHTML]="expandedEmotes | safe"></div>
